DATABASE_PROVIDER = "mysql"
DATABASE_HOST = "localhost"
DATABASE_USER = "root"
DATABASE_PASS = ""
DATABASE_NAME = "ecole"

SESSION_KEY_LENGTH = 24

TYPE_PERSON = 1
TYPE_EXPOSANT = 2
TYPE_STAFF = 3
TYPE_INTERVENANT = 4
TYPE_AUTEUR = 5